
export const defaultTable = [
  {
    id: "1",
    day: "Mon",
    startTime: "09:00",
    endTime: "17:00",
    location: "Office",
    ticked: true,
    cycleTime: 15,
  },
  {
    id: "2",
    day: "Tue",
    startTime: "09:00",
    endTime: "17:00",
    location: "Office",
    ticked: true,
    cycleTime: 15,
  },
  {
    id: "3",
    day: "Wed",
    startTime: "09:00",
    endTime: "17:00",
    location: "Office",
    ticked: true,
    cycleTime: 15,
  },
  {
    id: "4",
    day: "Thu",
    startTime: "09:00",
    endTime: "17:00",
    location: "Office",
    ticked: true,
    cycleTime: 15,
  },
  {
    id: "5",
    day: "Fri",
    startTime: "09:00",
    endTime: "17:00",
    location: "Office",
    ticked: true,
    cycleTime: 15,
  },
  {
    id: "6",
    day: "Sat",
    startTime: "9:00",
    endTime: "14:00",
    location: "",
    ticked: false,
    cycleTime: 15,
  },
  {
    id: "7",
    day: "Sun",
    startTime: "12:00",
    endTime: "18:00",
    location: "Beach",
    ticked: false,
    cycleTime: 15,
  },
]
